export const resourcesData: any[] = [
    {
        id: "1",
        title: "AI-Powered Resume Builder",
        description:
            "A Notion-based resume template powered by AI for quick customization.",
        file_url: "https://example.com/files/resume-builder.pdf",
        category: "Career",
        tags: ["resume", "notion", "ai", "productivity"],
        download_count: 1243,
        tool_used: "Notion",
        guide_url: "https://example.com/guides/resume-builder",
        video_url: "https://www.youtube.com/watch?v=xyz123abc",
        thumbnail_url: "/images/workflow-2.png",
        resource_type: "Template",
    },
    {
        id: "2",
        title: "Social Media Content Calendar",
        description:
            "Plan your weekly content with this customizable calendar in Google Sheets.",
        file_url: "https://example.com/files/content-calendar.xlsx",
        category: "Marketing",
        tags: ["calendar", "social media", "content", "google sheets"],
        download_count: 875,
        tool_used: "Google Sheets",
        guide_url: "https://example.com/guides/content-calendar",
        video_url: "https://www.youtube.com/watch?v=abcd9876",
        thumbnail_url: "https://example.com/thumbs/calendar-thumb.jpg",
        resource_type: "Spreadsheet",
    },
    {
        id: "3",
        title: "Automated Invoice Generator",
        description:
            "Generate invoices instantly using this Google Docs template and Zapier integration.",
        file_url: "https://example.com/files/invoice-generator.docx",
        category: "Finance",
        tags: ["invoice", "automation", "zapier", "template"],
        download_count: 432,
        tool_used: "Zapier",
        guide_url: "https://example.com/guides/invoice-generator",
        video_url: "https://www.youtube.com/watch?v=zapier101",
        thumbnail_url: "https://example.com/thumbs/invoice-thumb.jpg",
        resource_type: "Document",
    },
    {
        id: "4",
        title: "Beginner's Guide to ChatGPT Prompts",
        description:
            "A downloadable PDF guide to help you get started with crafting effective ChatGPT prompts.",
        file_url: "https://example.com/files/chatgpt-prompts-guide.pdf",
        category: "AI Tools",
        tags: ["chatgpt", "prompt", "guide", "pdf"],
        download_count: 2091,
        tool_used: "ChatGPT",
        guide_url: "https://example.com/guides/chatgpt-prompts",
        video_url: "https://www.youtube.com/watch?v=promptMastery",
        thumbnail_url: "https://example.com/thumbs/chatgpt-guide.png",
        resource_type: "Guide",
    },
    {
        id: "5",
        title: "Startup Landing Page Template",
        description:
            "A responsive HTML template for early-stage startups to showcase their product.",
        file_url: "https://example.com/files/landing-page-template.zip",
        category: "Web Development",
        tags: ["html", "template", "landing page", "startup"],
        download_count: 319,
        tool_used: "HTML/CSS",
        guide_url: "https://example.com/guides/landing-page-template",
        video_url: "https://www.youtube.com/watch?v=launchfast",
        thumbnail_url: "https://example.com/thumbs/startup-template.jpg",
        resource_type: "Code",
    },
];
